### ISSUE TITLE
Fix: Imports with .js suffix

### ISSUE THREAD

**Issue by Ademsk1** [nearform/playwright-firebase#100]
In the plugin, we import some files with their .js suffix, despite being in typescript. I think this was done to resolve Typescript errors, but in reality, the tsconfig.json probably needs some attention to fix this. 

e.g Instead of having 
```ts
import { addFirebaseScript, getToken } from './auth.setup.js'
```
We should have
```ts
import { addFirebaseScript, getToken } from './auth.setup'
```

**Comment by simoneb** [comment]
Yes, the source code in TS should only ever import code in TS and shouldn't even know that a JS build exists.
