### ISSUE TITLE
Create a CHANGELOG.md file

### ISSUE THREAD

**Issue by Ademsk1** [nearform/playwright-firebase#96]
We've (accidentally) jumped to 1.1.1! 🍾 🎆 🥳 
Let's create a CHANGELOG.md file so we can track the changes between new versions that users can collate with to easily identify any bugs that are around.

**Comment by simoneb** [comment]
There's no need for a change log, it's all tracked in GitHub releases.

**Comment by Ademsk1** [comment]
Yup, didn't see it on the right hand side of the github page :D
